export const SET_ROUTES_MENU = 'SET_ROUTES_MENU'
export const SET_PERMISSION_MENU = 'SET_PERMISSION_MENU'

export const LIST_TASKFLOW = 'LIST_TASKFLOW'

export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_USER_IDENTITY = 'SET_USER_IDENTITY'
export const SET_PROFESSOR_PROFILE = 'SET_PROFESSOR_PROFILE'

export const SET_ALL_SUBJECTS = 'SET_ALL_SUBJECTS'

export const SET_ALL_POSITIONS = 'SET_ALL_POSITIONS'

export const SET_ALL_ORGS = 'SET_ALL_ORGS'
