import Home from '@/views/Home.vue'
/* 报表 */
import business from '@/views/report/business/List'/* 运营报表 */
import profit from '@/views/report/profit/List'/* 利润报表 */
import roomstate from '@/views/report/roomstate/List'/* 房态报表 */
export default {
  path: '/',
  component: Home,
  name: '报表',
  iconCls: 'iconfont icon-ali-caidan2',
  children: [
    { path: '/business/boss',
      component: business,
      name: '运营报表',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/boss/store',
      component: business,
      hidden: true,
      name: '经营报表-运营统计-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/boss/roomtype',
      component: business,
      hidden: true,
      name: '经营报表--运营统计-基于房型',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/boss/room',
      component: business,
      hidden: true,
      name: '经营报表--经营统计-基于房间',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/outroom',
      component: business,
      hidden: true,
      name: '经营报表-出房报表--统计',
      meta: {
        desc: '经营报表：您可以下载不同维度的出房分析等。',
      },
    },
    { path: '/business/outroom/list',
      component: business,
      hidden: true,
      name: '经营报表-出房报表--统计列表',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/outroom/data',
      component: business,
      hidden: true,
      name: '经营报表-出房报表--数据可视化',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/money',
      component: business,
      hidden: true,
      name: '经营报表-收支报表',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/money/store',
      component: business,
      hidden: true,
      name: '经营报表-收支报表-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/money/room',
      component: business,
      hidden: true,
      name: '经营报表-收支报表-基于房间',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/business/money/person',
      component: business,
      hidden: true,
      name: '经营报表-收支报表-基于住户',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/summary',
      component: profit,
      name: '利润报表',
      meta: {
        desc: '利润报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/summary/store',
      component: profit,
      hidden: true,
      name: '利润报表-汇总-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/summary/storeshow',
      component: profit,
      hidden: true,
      name: '利润报表-汇总-基于门店可视化',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/summary/room',
      component: profit,
      hidden: true,
      name: '利润报表-汇总-基于房间',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/type',
      component: profit,
      hidden: true,
      name: '利润报表-按科目-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/type/store',
      component: profit,
      hidden: true,
      name: '利润报表-按科目-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/type/person',
      component: profit,
      hidden: true,
      name: '利润报表-按科目-基于住户',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/type/room',
      component: profit,
      hidden: true,
      name: '利润报表-按科目-基于房间',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/month',
      component: profit,
      hidden: true,
      name: '利润报表-按月度-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/month/store',
      component: profit,
      hidden: true,
      name: '利润报表-按月度-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/month/person',
      component: profit,
      hidden: true,
      name: '利润报表-按月度-基于住户',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/profit/month/room',
      component: profit,
      hidden: true,
      name: '利润报表-按月度-基于门店',
      meta: {
        desc: '经营报表：您可以下载不同维度的运营分析，如房态出租率、房态空置率等。',
      },
    },
    { path: '/roomstate',
      component: roomstate,
      name: '房态报表',
      meta: {
        desc: '房态报表：您可以下载不同维度的房态分析，如房态出租率、房态空置率等。',
      },
    },
    // { path: '/roomstatus', component: roomstatus, name: '房态报表' },
  ],
}
